---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jest/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
rules:
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "react/display-name": off
  "react/prop-types": off
  "arrow-spacing": error
  "curly": error
  "no-duplicate-imports": error
  "no-multi-assign": error
  "no-multiple-empty-lines": error
  "no-var": error
settings:
  react:
    version: detect
env:
  jest: true
  node: true
